### ISSUE TITLE
[Crash Report] NoClassDefFound Exception

### ISSUE THREAD

**Issue by Desempregago** [Vazkii/PotionFingers#2]
https://gist.github.com/Fogrits/622f2f72d4dd97f701a0b33d3af4f5ba

**Comment by Vazkii** [comment]
Send the full log over gist or pastebin please.

**Comment by Desempregago** [comment]
done

**Comment by 3TUSK** [comment]
@Vazkii 
https://github.com/Vazkii/PotionFingers/blob/09b5aa62a3bfba206e0b01a9e4bdb030e4b8608d/src/main/java/vazkii/potionfingers/PotionFingers.java#L22
You reversed the dependency for PotionFingers. Should be `required-after:autoreglib`.

**Comment by Sunconure11** [comment]
https://pastebin.com/knb6Muv0

Encountering the same issue upon startup.
