### ISSUE TITLE
[Suggestion[

### ISSUE THREAD

**Issue by D3nnis3n** [Vazkii/PotionFingers#4]
I love your mod. Would it be possible you could make it more General, so People could use ANY potion effect (included modded ones) that are available in a mod pack on a ring. E.g. by crafting the ring and then putting some of those potions to it, or something else? Als rings are limited to two and you Need to carry the same ring twice for the higher Level that still seems balanced for me.

**Comment by Vazkii** [comment]
Check the crafttweaker documentation in the CF page. This can be done by the pack author.
